In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Titanic-Dataset (1).csv to Titanic-Dataset (1).csv


In [4]:
df = pd.read_csv('Titanic-Dataset (1).csv')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [5]:
print("Jumlah baris dan kolom:", df.shape)
print(df.columns)

Jumlah baris dan kolom: (891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [9]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [11]:
print(df.columns.tolist())
print(df.shape)

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
(891, 12)


In [12]:
y = df['Survived']

In [13]:
X = df.drop(columns=['PassengerId', 'Survived'])

In [14]:
print("X:")
print(X.head())

print("\ny:")
print(y.head())

X:
   Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S  

y:
0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64


In [15]:
X = df[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']]
y = df['Survived']

print(X.head())
print(y.head())

   Pclass   Age  SibSp  Parch     Fare
0       3  22.0      1      0   7.2500
1       1  38.0      1      0  71.2833
2       3  26.0      0      0   7.9250
3       1  35.0      1      0  53.1000
4       3  35.0      0      0   8.0500
0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64


In [16]:
print(X.isnull().sum())

Pclass      0
Age       177
SibSp       0
Parch       0
Fare        0
dtype: int64


In [17]:
X['Age'] = X['Age'].fillna(X['Age'].median())

/tmp/ipykernel_1452/1341152632.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Age'] = X['Age'].fillna(X['Age'].median())


In [18]:
print(X.isnull().sum())

Pclass    0
Age       0
SibSp     0
Parch     0
Fare      0
dtype: int64


In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled[:5])

[[ 0.82956755 -0.11207776 -0.46508428 -0.46618317  0.5138115 ]
 [-0.37094484 -0.11207776 -0.46508428 -0.46618317 -0.66256323]
 [-1.57145722 -0.11207776 -0.46508428 -0.46618317  3.95539858]
 [ 0.82956755 -0.87980748 -0.46508428  0.72778236 -0.46787435]
 [-0.37094484  0.11824116  0.47833454  0.72778236 -0.11597681]]


In [21]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=3)

X_train_selected = selector.fit_transform(X_train_scaled, y_train)
X_test_selected = selector.transform(X_test_scaled)

print("Bentuk sebelum feature selection:", X_train_scaled.shape)
print("Bentuk setelah feature selection:", X_train_selected.shape)

Bentuk sebelum feature selection: (712, 5)
Bentuk setelah feature selection: (712, 3)


In [22]:
selected_features = X.columns[selector.get_support()]

print("Fitur yang terpilih:")
print(selected_features.tolist())

Fitur yang terpilih:
['Pclass', 'Parch', 'Fare']


In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_selected, y_train)

y_pred = model.predict(X_test_selected)

In [24]:
from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.6424581005586593

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.81      0.74       110
           1       0.55      0.38      0.45        69

    accuracy                           0.64       179
   macro avg       0.61      0.59      0.59       179
weighted avg       0.63      0.64      0.62       179



In [25]:
results = []

for k in range(1, X.shape[1] + 1):

    selector = SelectKBest(score_func=f_classif, k=k)

    X_train_selected = selector.fit_transform(X_train_scaled, y_train)
    X_test_selected = selector.transform(X_test_scaled)

    model = LogisticRegression(max_iter=1000)

    model.fit(X_train_selected, y_train)

    y_pred = model.predict(X_test_selected)

    accuracy = accuracy_score(y_test, y_pred)

    results.append([k, accuracy])

results_df = pd.DataFrame(
    results,
    columns=['Jumlah Fitur', 'Accuracy']
)

print(results_df)

   Jumlah Fitur  Accuracy
0             1  0.642458
1             2  0.642458
2             3  0.642458
3             4  0.664804
4             5  0.675978


In [26]:
best_result = results_df.loc[
    results_df['Accuracy'].idxmax()
]

print("Jumlah fitur optimal:", best_result['Jumlah Fitur'])
print("Accuracy terbaik:", best_result['Accuracy'])

Jumlah fitur optimal: 5.0
Accuracy terbaik: 0.6759776536312849


In [27]:
best_k = int(best_result['Jumlah Fitur'])

selector = SelectKBest(
    score_func=f_classif,
    k=best_k
)

selector.fit(X_train_scaled, y_train)

selected_features = X.columns[selector.get_support()]

print("Jumlah fitur optimal:", best_k)
print("Fitur yang terpilih:")
print(selected_features.tolist())

Jumlah fitur optimal: 5
Fitur yang terpilih:
['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']


In [28]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.6759776536312849

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.85      0.76       110
           1       0.62      0.41      0.49        69

    accuracy                           0.68       179
   macro avg       0.66      0.63      0.63       179
weighted avg       0.67      0.68      0.66       179



### Jawaban Nomor 7

Berdasarkan hasil analisis, jumlah fitur optimal adalah 5 fitur, yaitu Pclass, Age, SibSp, Parch, dan Fare. Model Logistic Regression menghasilkan accuracy terbaik sebesar 67,60% ketika menggunakan kelima fitur tersebut.